require 'rspec/core/rake_task'
require 'rubocop/rake_task'
require 'foodcritic'

namespace :style do
  desc 'Execute Rubocop for Ruby style checks'
  RuboCop::RakeTask.new(:ruby) do |task|
    task.options = %w(--display-cop-names --display-style-guide)
  end

  desc 'Execute Foodcritic for Chef linting'
  FoodCritic::Rake::LintTask.new(:chef) do |task|
    task.options = {
      fail_tags: %w(any)
    }
  end
end

namespace :integration do
  desc 'Execute Test Kitchen for integration testing'
  task :vagrant do
    Kitchen.logger = Kitchen.default_file_logger
    Kitchen::Config.new.instances.each do |instance|
      instance.test(:always)
    end
  end
end

desc 'Execute Rubocop and Foodcritic'
task style: %w(style:ruby style:chef)

desc 'Execute ChefSpec for unit testing'
RSpec::Core::RakeTask.new(:spec)

task default: %w(style spec integration:vagrant)
