name             'nw-base'
maintainer       'RSA Security, LLC'
maintainer_email 'support@rsa.com'
license          'Proprietary - All Rights Reserved'
description      'Performs base tasks for all Netwitness components'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.2.3'
supports         'centos', '>= 7'
depends          'firewall', '~> 2.5.2'
chef_version     '>= 12'
source_url       'file:///dev/null'
issues_url       'file:///dev/null'
