source 'https://rubygems.org'

group :lint do
  gem 'foodcritic', '~> 7.0'
  gem 'rubocop', '~> 0.41'
end

group :unit do
  gem 'berkshelf', '~> 4.3'
  gem 'chefspec', '~> 4.7'
end

group :integration do
  gem 'test-kitchen', '~> 1.10'
  gem 'kitchen-vagrant', '~> 0.20'
  gem 'kitchen-inspec', '~> 0.15'
end
