source 'https://supermarket.chef.io/'

cookbook 'nw-archiver', path: 'nw-archiver'
cookbook 'nw-base', path: 'nw-base'
cookbook 'nw-broker', path: 'nw-broker'
cookbook 'nw-concentrator', path: 'nw-concentrator'
cookbook 'nw-decoder', path: 'nw-decoder'
cookbook 'nw-event-stream-analysis', path: 'nw-event-stream-analysis'
cookbook 'nw-log-collector', path: 'nw-log-collector'
cookbook 'nw-log-decoder', path: 'nw-log-decoder'
cookbook 'nw-malware-analysis', path: 'nw-malware-analysis'
cookbook 'nw-repositories', path: 'nw-repositories'
cookbook 'nw-server', path: 'nw-server'
cookbook 'rsa-admin-server', path: 'rsa-admin-server'
cookbook 'rsa-cms-server', path: 'rsa-cms-server'
cookbook 'rsa-config-server', path: 'rsa-config-server'
cookbook 'rsa-contexthub', path: 'rsa-contexthub'
cookbook 'rsa-esa-analytics-server', path: 'rsa-esa-analytics-server'
cookbook 'rsa-investigate', path: 'rsa-investigate'
cookbook 'rsa-orchestration-server', path: 'rsa-orchestration-server'
cookbook 'rsa-response', path: 'rsa-response'
cookbook 'rsa-security-server', path: 'rsa-security-server'
